server.ssl.enabled=${SERVER_SSL_ENABLED:false}  
server.error.include-stacktrace=on_param
server.error.include-message=always
server.error.include-binding-errors=always

spring.mvc.pathmatch.matching-strategy=ant_path_matcher
spring.web.resources.add-mappings=true
spring.mvc.log-request-details=false

logging.level.com.unlu.alimtrack.config.DotenvEnvironmentPostProcessor=DEBUG
spring.jpa.properties.hibernate.default_batch_fetch_size=100
spring.jpa.properties.hibernate.jdbc.batch_size=20
spring.jpa.properties.hibernate.order-inserts=true
spring.jpa.properties.hibernate.jdbc.time_zone=America/Argentina/Buenos_Aires

spring.jackson.deserialization.fail-on-unknown-properties=false
spring.jackson.deserialization.fail-on-ignored-properties=false
spring.jackson.serialization.fail-on-empty-beans=false
spring.jackson.serialization.fail-on-self-references=false
server.port=8080
server.address=0.0.0.0
jwt.secret=${JWT_SECRET}

# metricas a grafana
management.endpoints.web.exposure.include=health,info,metrics

management.otlp.metrics.export.resource-attributes.[service.name]=alimtrack-backend
management.otlp.metrics.export.resource-attributes[application]=alimtrack-backend
management.otlp.metrics.export.resource-attributes.service.version=1.0.0
management.otlp.metrics.export.url=${GRAFANA_OTLP_URL}
management.otlp.metrics.export.headers.[Authorization]=Basic ${GRAFANA_AUTH_TOKEN}
management.otlp.metrics.export.step=1m
management.otlp.metrics.export.enabled=true


# Perfil activo
spring.profiles.active=${SPRING_PROFILES_ACTIVE:prod}