# ==================== CONFIG BASE ====================
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.mvc.pathmatch.matching-strategy=ant_path_matcher
# ==================== SERVER ====================
server.address=${ALIMTRACK_SERVER_ADDRESS:0.0.0.0}
server.port=${ALIMTRACK_SERVER_PORT:8080}
# ==================== JACKSON ====================
spring.jackson.serialization.fail-on-empty-beans=false
spring.jackson.serialization.fail-on-self-references=false
# ==================== LOGGING ====================
logging.level.org.hibernate.SQL=info
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=info
logging.level.com.unlu.alimtrack=info
logging.level.org.springframework=INFO
logging.level.org.apache=WARN
logging.level.org.hibernate=INFO
# ==================== PERFORMANCE ====================
spring.jpa.properties.hibernate.jdbc.time_zone=UTC
spring.jpa.properties.hibernate.default_batch_fetch_size=20
spring.jpa.properties.hibernate.jdbc.batch_size=20
spring.jpa.properties.hibernate.order_inserts=true
# ==================== PROFILES ====================
spring.profiles.active=dev
# ==================== SECURITY ====================
spring.security.user.name=user
spring.security.user.password=123456
spring.security.user.roles=USER



