# ==================== CONFIG BASE ====================
spring.config.import=file:env.properties

spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.show-sql=false
# ==================== SERVER ====================
server.address=${SERVER_ADDRESS:0.0.0.0}
server.port=${SERVER_PORT:8080}

# ==================== JACKSON ====================
spring.jackson.serialization.fail-on-empty-beans=false
spring.jackson.serialization.fail-on-self-references=false

# ==================== LOGGING ====================
logging.level.org.hibernate.SQL=WARN
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=WARN
logging.level.com.unlu.alimtrack=DEBUG

# ==================== PERFORMANCE ====================
spring.jpa.properties.hibernate.default_batch_fetch_size=20
spring.jpa.properties.hibernate.jdbc.batch_size=20
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.order_updates=true

# ==================== PROFILES ====================
spring.profiles.active=dev

# Configuración DevTools
spring.devtools.restart.enabled=true
spring.devtools.livereload.enabled=true
spring.devtools.add-properties=true

spring.devtools.restart.trigger-file=.trigger
# DevTools SUPER agresivo
spring.devtools.restart.poll-interval=500
spring.devtools.restart.quiet-period=100
